services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omartobon-backend
    ports:
      - "8080:80"
    volumes:
      - ../www:/var/www/html
    # env_file:
    #   - ../.env.example
